-- Tabela Estados
CREATE TABLE ESTADOS(
	CODIGO NUMBER(9) NOT NULL,
	NOME VARCHAR2(255),
	SIGLA VARCHAR(2),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ESTADOS ADD CONSTRAINT PK_CODIGO_ESTADO PRIMARY KEY (CODIGO);

-- Tabela Cidades
CREATE TABLE CIDADES(
	CODIGO NUMBER(9) NOT NULL,
	DESCRICAO VARCHAR2(255) NOT NULL,
	UF VARCHAR2(2) NOT NULL,
	CODIGOIBGE VARCHAR2(255) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE CIDADES ADD CONSTRAINT PK_CODIGO_CIDADE PRIMARY KEY (CODIGO);

-- Tabela Clientes
CREATE TABLE CLIENTES(
	CODIGO NUMBER(9) NOT NULL,
	NOMEFANTASIA VARCHAR2(255) NOT NULL,
	RAZAOSOCIAL VARCHAR2(255) NOT NULL,
	INSCRICAO VARCHAR2(255) NOT NULL,
	TIPOINSCRICAO NUMBER(1) NOT NULL,
	UF VARCHAR2(2) NOT NULL,
	INSCRICAOESTADUAL VARCHAR2(30) NOT NULL,
	INSCRICAOMUNICIPAL VARCHAR2(30) NOT NULL,
	DDD NUMBER(2) NOT NULL,
	FONE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	DATACADASTRO DATE,
	TIPOENDERECO NUMBER(1),
	ENDERECO VARCHAR2(255) NOT NULL,
	BAIRRO VARCHAR2(255) NOT NULL,
	CODIGOCIDADE NUMBER(4),
	CEP VARCHAR2(8) NOT NULL,
	NUMERO NUMBER(5),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO);

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CODIGOCIDADE) REFERENCES CIDADES (CODIGO);

CREATE INDEX IDX_CLIENTE_FANTASIA ON CLIENTES (NOMEFANTASIA);

CREATE INDEX IDX_CLIENTE_DTCAD ON CLIENTES (DATACADASTRO);


-- Tabela Forecedores
CREATE TABLE FORNECEDORES(
	CODIGO NUMBER(9) NOT NULL,
	NOMEFANTASIA VARCHAR2(255) NOT NULL,
	RAZAOSOCIAL VARCHAR2(255) NOT NULL,
	INSCRICAO VARCHAR2(255) NOT NULL,
	TIPOINSCRICAO NUMBER(1) NOT NULL,
	UF VARCHAR2(2) NOT NULL,
	INSCRICAOESTADUAL VARCHAR2(30),
	INSCRICAOMUNICIPAL VARCHAR2(30),
	DDD NUMBER(2) NOT NULL,
	FONE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	DATACADASTRO DATE,
	TIPOENDERECO NUMBER(1),
	ENDERECO VARCHAR2(255) NOT NULL,
	BAIRRO VARCHAR2(255) NOT NULL,
	CODIGOCIDADE NUMBER(4),
	CEP VARCHAR2(8) NOT NULL,
	NUMERO NUMBER(5),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE FORNECEDORES ADD CONSTRAINT PK_CODIGO_FORNECE PRIMARY KEY (CODIGO);

ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDOR_CIDADE FOREIGN KEY (CODIGOCIDADE) REFERENCES CIDADES (CODIGO);

CREATE INDEX IDX_FORNECEDOR_FANTASIA ON FORNECEDORES (NOMEFANTASIA);

CREATE INDEX IDX_FORNECEDOR_DTCAD ON FORNECEDORES (DATACADASTRO);

-- Tabela Produtos
CREATE TABLE PRODUTOS(
	CODIGO NUMBER(14) NOT NULL,
	DESCRICAO VARCHAR2(255) NOT NULL,
	CODIGOBARRAS VARCHAR2(13)
   NCM VARCHAR(20),
	VALORUNITARIO NUMBER(15,4) DEFAULT 0,
	QUANTIDADEINICIAL NUMBER(15,4) DEFAULT 0
)

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_CODIGO_PRODUTO PRIMARY KEY (CODIGO);

CREATE INDEX IDX_DESCRICAO_PRODUTO ON PRODUTOS (DESCRICAO);

CREATE TABLE ENTRADAS(
	CODIGO NUMBER(9) NOT NULL,
	VALORCONTABIL NUMBER(15,4) NOT NULL DEFAULT 0,
	VALORDESCONTO NUMBER(15,4) NOT NULL DEFAULT 0,
	VALORACRESCIMO NUMBER(15,4) NOT NULL DEFAULT 0,
)






