-- Tabela Paises
CREATE TABLE PAISES(
	CODIGO NUMBER(9) NOT NULL,
	NOME VARCHAR2(255) NOT NULL,
	CODIGO_BANCO_CENTRAL NUMBER(9)
);

ALTER TABLE PAISES ADD CONSTRAINT PK_CODIGO_PAIS PRIMARY KEY (CODIGO);

-- Tabela Estados
CREATE TABLE ESTADOS(
	CODIGO NUMBER(9) NOT NULL,
	NOME VARCHAR2(255) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
	CODIGO_PAIS NUMBER(9) NOT NULL
);

ALTER TABLE ESTADOS ADD CONSTRAINT PK_CODIGO_ESTADO PRIMARY KEY (CODIGO);
ALTER TABLE ESTADOS ADD CONSTRAINT FK_CODIGO_PAIS FOREIGN KEY (CODIGO_PAIS) REFERENCES PAISES (CODIGO);

-- Tabela Cidades
CREATE TABLE CIDADES(
	CODIGO NUMBER(9) NOT NULL,
	NOME VARCHAR2(255) NOT NULL,
	CODIGO_ESTADO INTEGER NOT NULL,
	CODIGOIBGE VARCHAR2(255),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE CIDADES ADD CONSTRAINT PK_CODIGO_CIDADE PRIMARY KEY (CODIGO);
ALTER TABLE CIDADES ADD CONSTRAINT FK_CODIGO_CIDADE FOREIGN KEY (CODIGO_ESTADO) REFERENCES ESTADOS (CODIGO);

-- Tabela Clientes
CREATE TABLE CLIENTES(
	CODIGO NUMBER(9) NOT NULL,
	NOMEFANTASIA VARCHAR2(255) NOT NULL,
	RAZAOSOCIAL VARCHAR2(255) NOT NULL,
	INSCRICAO VARCHAR2(255) NOT NULL,
	TIPOINSCRICAO NUMBER(1) NOT NULL,
	CODIGO_CIDADE NOT NULL,
	INSCRICAOESTADUAL VARCHAR2(30) NOT NULL,
	INSCRICAOMUNICIPAL VARCHAR2(30) NOT NULL,
	DDD NUMBER(2) NOT NULL,
	FONE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	DATACADASTRO DATE,
	TIPOENDERECO NUMBER(1),
	ENDERECO VARCHAR2(255) NOT NULL,
	BAIRRO VARCHAR2(255) NOT NULL,
	CODIGOCIDADE NUMBER(4),
	CEP VARCHAR2(8) NOT NULL,
	NUMERO NUMBER(5),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO);

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CODIGOCIDADE) REFERENCES CIDADES (CODIGO);

CREATE INDEX IDX_CLIENTE_FANTASIA ON CLIENTES (NOMEFANTASIA);

CREATE INDEX IDX_CLIENTE_DTCAD ON CLIENTES (DATACADASTRO);


-- Tabela Forecedores
CREATE TABLE FORNECEDORES(
	CODIGO NUMBER(9) NOT NULL,
	NOMEFANTASIA VARCHAR2(255) NOT NULL,
	RAZAOSOCIAL VARCHAR2(255) NOT NULL,
	INSCRICAO VARCHAR2(255) NOT NULL,
	TIPOINSCRICAO NUMBER(1) NOT NULL,
	UF VARCHAR2(2) NOT NULL,
	INSCRICAOESTADUAL VARCHAR2(30),
	INSCRICAOMUNICIPAL VARCHAR2(30),
	DDD NUMBER(2) NOT NULL,
	FONE VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	DATACADASTRO DATE,
	TIPOENDERECO NUMBER(1),
	ENDERECO VARCHAR2(255) NOT NULL,
	BAIRRO VARCHAR2(255) NOT NULL,
	CODIGOCIDADE NUMBER(4),
	CEP VARCHAR2(8) NOT NULL,
	NUMERO NUMBER(5),
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE FORNECEDORES ADD CONSTRAINT PK_CODIGO_FORNECE PRIMARY KEY (CODIGO);

ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDOR_CIDADE FOREIGN KEY (CODIGOCIDADE) REFERENCES CIDADES (CODIGO);

CREATE INDEX IDX_FORNECEDOR_FANTASIA ON FORNECEDORES (NOMEFANTASIA);

CREATE INDEX IDX_FORNECEDOR_DTCAD ON FORNECEDORES (DATACADASTRO);

-- Tabela Grupos de produtos
CREATE GRUPOS_PRODUTOS(
	CODIGO NUMBER(9) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	DESCRICAO VARCHAR2(255)
)

ALTER TABLE GRUPOS_PRODUTOS ADD CONSTRAINT PK_CODIGO_GRUPO PRIMARY KEY (CODIGO);

-- Tabela Produtos
CREATE TABLE PRODUTOS(
	CODIGO NUMBER(14) NOT NULL,
	DESCRICAO VARCHAR2(255) NOT NULL,
	CODIGOGRUPO NUMBER(9) NOT NULL,
	CODIGOBARRAS VARCHAR2(13),
	NCM VARCHAR(20),
	QUANTIDADEINICIAL NUMBER(15,4) DEFAULT 0,
	CODIGOUNIDADE NUMBER(9) NOT NULL
)

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_CODIGO_PRODUTO PRIMARY KEY (CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_GRUPOS FOREIGN KEY (CODIGOGRUPO) REFERENCES GRUPOS_PRODUTOS (CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_GRUPOS FOREIGN KEY (CODIGOGRUPO) REFERENCES GRUPOS_PRODUTOS (CODIGO);
CREATE INDEX IDX_DESCRICAO_PRODUTO ON PRODUTOS (DESCRICAO);

-- Tabela Produtos Valor Cliente

CREATE TABLE PRODUTOS_VALOR_CLIENTE(
	CODIGOPRODUTO NUMBER(14) NOT NULL,
	CODIGOCLIENTE NUMBER(9) NOT NULL,
	VALORUNITARIO NUMBER(15,4) DEFAULT 0
)

ALTER TABLE PRODUTOS_VALOR_CLIENTE ADD CONSTRAINT PK_PRODUTO_CLIENTE (CODIGOPRODUTO, CODIGOCLIENTE);
ALTER TABLE PRODUTOS_VALOR_CLIENTE ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (CODIGOPRODUTO) REFERENCES PRODUTOS (CODIGO);
ALTER TABLE PRODUTOS_VALOR_CLIENTE ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTES (CODIGO);

-- Tabela Entradas

CREATE TABLE ENTRADAS(
	CODIGO NUMBER(9) NOT NULL,
	NUMERO NUMBER(9) NOT NULL,
	SERIE VARCHAR2(15),
	SUBSERIE VARCHAR2(15),
	CODIGOCLIENTE NUMBER(9) NOT NULL,
	DATAEMISSAO DATE NOT NULL,
	DATAENTRADA DATE NOT NULL,
	VALORCONTABIL NUMBER(15,4) NOT NULL DEFAULT 0,
	VALORDESCONTO NUMBER(15,4) NOT NULL DEFAULT 0,
	VALORACRESCIMO NUMBER(15,4) NOT NULL DEFAULT 0,
)

ALTER TABLE ENTRADAS ADD CONSTRAINT PK_CODIGO_ENTRADA (CODIGO);
CREATE UNIQUE INDEX IDX_ENTRADA_UNICA ON ENTRADAS (NUMERO, SERIE, SUBSERIE, CODIGOCLIENTE);





